modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "confluence"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.confluence]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.confluence]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

#[[dependencies.confluence]]
#modId="eventhorizon"
#mandatory=true
#versionRange="[1.20.1-1.1.0,)"
#ordering="NONE"
#side="CLIENT"

#[[dependencies.confluence]]
#modId="geckolib"
#mandatory=true
#versionRange="[4.4.2,)"
#ordering="NONE"
#side="CLIENT"

#[[dependencies.confluence]]
#modId="fusion"
#mandatory=true
#versionRange="[1.1.1,)"
#ordering="NONE"
#side="CLIENT"